name: "Build Status Action"
description: "Returns build results"

outputs:
  result:
    description: "Build result"


runs:
  using: "composite"
  
  steps:
    - name: Set Output 
      run: echo "result=Build Successful" >> $GITHUB_OUTPUT

